# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
    ]
