# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_uploadfilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
