# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_delete_uploadfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputcase',
            name='answer_case_text',
            field=models.TextField(default=datetime.datetime(2016, 4, 3, 8, 29, 15, 735735, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputcase',
            name='points',
            field=models.IntegerField(default=5),
        ),
    ]
