# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_auto_20160403_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputcase',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
