# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('C', 'C'), ('J', 'Java')], max_length=1)),
                ('question_no', models.IntegerField()),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('language', 'question_no')]),
        ),
        migrations.AddField(
            model_name='inputcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.Question'),
        ),
    ]
