# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammcqanswer',
            name='question_no',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='teammcqanswer',
            unique_together=set([('question_no', 'team')]),
        ),
    ]
