# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20160223_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lang_pref',
            field=models.CharField(max_length=10, null=True, verbose_name='programming language preference'),
        ),
    ]
