# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_lang_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lang_pref',
            field=models.CharField(choices=[('C', 'C'), ('J', 'Java')], max_length=10, null=True, verbose_name='programming language preference'),
        ),
    ]
