# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20160305_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammcqanswer',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='teammcqanswer',
            name='choice_id',
            field=models.IntegerField(default=0),
        ),
    ]
