# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_auto_20160402_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coding_start_time',
            field=models.DateTimeField(null=True, verbose_name='coding start time'),
        ),
    ]
