# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 20:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_team_coding_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='college_id',
            field=models.CharField(default='55555', max_length=5, validators=[django.core.validators.MinLengthValidator(5, 'Invalid College ID')], verbose_name='college id'),
        ),
    ]
