# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 20:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_teammember_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='college_id',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5,5}$', 'Invalid College ID')], verbose_name='college id'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='mobile_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10,10}$', 'Invalid Mobile Number')], verbose_name='mobile number'),
        ),
    ]
