# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-16 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_auto_20160407_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mcqs_start_time',
            field=models.DateTimeField(null=True, verbose_name='mcqs start time'),
        ),
    ]
