# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0003_auto_20160402_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_choice_no',
            field=models.IntegerField(default=0),
        ),
    ]
