# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('language', 'question_no')]),
        ),
    ]
