# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import mcqs.models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0002_auto_20160131_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(default=mcqs.models.Question.incre_question_count, unique=True),
        ),
    ]
