# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='team',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin status'),
        ),
    ]
