# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20160214_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'team member', 'verbose_name_plural': 'team members'},
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.SlugField(max_length=25, unique=True, verbose_name='team name'),
        ),
    ]
