# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20160305_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lang_pref',
            field=models.CharField(choices=[('C', 'C'), ('J', 'Java')], default='0', max_length=1, verbose_name='programming language preference'),
        ),
    ]
