# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 18:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20160327_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='mobile_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10, 'Invalid Mobile Number')], verbose_name='mobile number'),
        ),
    ]
