# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20160331_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammcqanswer',
            old_name='choice_id',
            new_name='choice_no',
        ),
        migrations.AlterUniqueTogether(
            name='teammcqanswer',
            unique_together=set([('question_no', 'choice_no', 'team')]),
        ),
    ]
